### ISSUE TITLE
Running AFNI GLM with 400 regressors

### ISSUE THREAD

**Issue by romasalah** [mvdoc/identity-decoding#2]
Hi Dr. Castello,

I tried to replicate the published results using, but got slightly different results, then noticed that my GLMs have 260 regressors because it models only one task in each GLM (10 runs x 1 types of familiarity × 4 identities × 5 head-views) and that in the paper you mentioned this "Each image was modelled separately within each run, yielding 400 regressors of interest (10 runs × 2 types of familiarity × 4 identities × 5 head-views)".

The problem is that the code forces me to specify a task if I want to model each run in the GLM using `-estimate-within-run` and you mentioned the reason for that in the code comments 

   

>  1. It computes betas within each run (instead of across the entire experiment) using a standard gamma HRF (one beta for each stimulus)  2. It computes the GLM within familiar / stranger stimuli only. This is done to reduce runtime since a giganormous matrix needs to be inverted otherwise.

My question is, should I override this check and force the GLM to run using `-estimate-within-run` and both types of familiarity in the same GLM to replicate the published results?

**Comment by mvdoc** [comment]
Hi @romasalah,
Thanks for pointing this out. The description of the methods in the paper is imprecise, and the comment in the code is correct: the GLM is estimated separately for the personally familiar and the visually familiar tasks. So each of the two GLMs should have 200 regressors of interest (10 runs x 1 type of familiarity x 4 identities x 5 head-views), plus the nuisance regressors. 

However, note that because personally familiar and visually familiar images are blocked within each run, there shouldn't be any difference in the estimated parameters if you estimated two separate GLMs for each task or a single GLM with both tasks. The only difference will be in the size of the matrix to be inverted for estimating the models, so that's why I ended up fitting the GLM within each task separately.

Hope this clarifies it,
Matteo

**Comment by romasalah** [comment]
Thanks for your quick answer and clarification. Great, so I don't need to do the huge GLM then. I appreciate your help greatly  :)
